### ISSUE TITLE
同步镜像到腾讯云和猪齿鱼harbor报错

### ISSUE THREAD

**Issue by carllhw** [TimeBye/registry-manager#1]
E0127 18:16:22.404231      32 copy.go:37] 同步镜像出错：time="2023-01-27T18:16:21Z" level=fatal msg="Error creating an updated image manifest: Error preparing updated manifest, layer \"sha256:d1d2d2b62183f42347b38301545792220f143b29d9066959ef4d9b1c4f1ea767\": unsupported MIME type for compression: application/vnd.in-toto+json"

https://github.com/containers/skopeo/issues/1874
镜像setzero/registry-manager，需要使用新版本的skopeo

**Comment by TimeBye** [comment]
谢谢反馈，我重新构建一下镜像
